### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by lhs55502002** [Tatsh/patreon-archiver#21]
I know how to use yt-dlp and I am familiar with it,but when I did as the usage,it just didn't work.How to use it?The campaign ID should be right .

<img width="1280" alt="屏幕截图 2023-07-30 212820" src="https://github.com/Tatsh/patreon-archiver/assets/62332619/6d5fed85-e96a-4899-aafb-8cc4370f9b00">

**Comment by Tatsh** [comment]
This error means extracting cookies from Chrome did not work. Which browser are you wanting to get cookies from? The default is Chrome (`--browser chrome`). The options are:

- brave
- chrome
- chromium
- edge
- firefox
- opera
- safari
- vivaldi

It can generally read from any updated Chromium browser and Firefox. The code does not detect Beta/Canary versions.

For the moment patreon-archiver only supports getting cookies via yt-dlp's `extract_cookies_from_browser()`.

**Comment by lhs55502002** [comment]
I use --browser edge,and it works.Thank you!

Maybe it's due to the odd problem of extracting cookies from chrome recently.I don't know why I can't extract cookies from chrome when I use yt-dlp since two days ago,so I turn to use edge for yt-dlp.Now it works for patreon-archiver.
